{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "sql",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "code",
            "source": [
                "USE BaseBall_Summer_2023;\r\n",
                "IF OBJECT_ID (N'dbo.[Parks]', N'U') IS NOT NULL\r\n",
                "DROP TABLE dbo.[Parks];\r\n",
                "GO\r\n",
                "CREATE TABLE Parks (\r\n",
                "  parkID char(5),\r\n",
                "  parkName varchar(100) NOT NULL,\r\n",
                "  parkAlias varchar(100),\r\n",
                "  city varchar(50),\r\n",
                "  state varchar(50),\r\n",
                "  country char(2),\r\n",
                "  primary key (parkID),\r\n",
                "--   foreign key (parkID) references dbo.HomeGames\r\n",
                ");\r\n",
                "\r\n",
                "-- Alter table Parks\r\n",
                "-- Alter column [Parks_PK] varchar(255) Not Null\r\n",
                "-- ADD PRIMARY KEY (parkID)\r\n",
                "\r\n",
                "ALTER TABLE Parks\r\n",
                "ADD CONSTRAINT check_Country CHECK (country in ('AU', 'CA', 'JP', 'MX', 'PR', 'UK', 'US'))\r\n",
                "\r\n",
                "-- Alter table Parks\r\n",
                "-- Add Constraint FK_parkID Foreign key (parkID)\r\n",
                "-- References HomeGames(parkID)\r\n",
                "-- On delete cascade\r\n",
                "-- On Update cascade\r\n",
                "\r\n",
                "\r\n",
                "\r\n",
                "Use BaseBall_Summer_2023;\r\n",
                "Delete from Parks\r\n",
                "INSERT INTO Parks VALUES ('ALB01','Riverside Park',null,'Albany','NY','US'),\r\n",
                "('ALT01','Columbia Park',null,'Altoona','PA','US'), ('ANA01','Angel Stadium of\r\n",
                "Anaheim','Edison Field; Anaheim Stadium','Anaheim','CA','US'), ('ARL01','Arlington\r\n",
                "Stadium',null,'Arlington','TX','US'), ('ARL02','Rangers Ballpark in Arlington','The\r\n",
                "Ballpark in Arlington; Ameriquest Fl','Arlington','TX','US'), ('ATL01','Atlanta-\r\n",
                "Fulton County Stadium',null,'Atlanta','GA','US'), ('ATL02','Turner\r\n",
                "Field',null,'Atlanta','GA','US'), ('ATL03','Suntrust\r\n",
                "Park',null,'Atlanta','GA','US'), ('BAL01','Madison Avenue\r\n",
                "Grounds',null,'Baltimore','MD','US'), ('BAL02','Newington\r\n",
                "Park',null,'Baltimore','MD','US'), ('BAL03','Oriole Park\r\n",
                "I',null,'Baltimore','MD','US'), ('BAL04','Belair Lot',null,'Baltimore','MD','US'),\r\n",
                "('BAL05','Monumental Park',null,'Baltimore','MD','US'), ('BAL06','Oriole Park\r\n",
                "II',null,'Baltimore','MD','US'), ('BAL07','Oriole Park\r\n",
                "III',null,'Baltimore','MD','US'), ('BAL09','Oriole Park IV','American League\r\n",
                "Park','Baltimore','MD','US'), ('BAL10','Terrapin Park','Oriole Park\r\n",
                "V','Baltimore','MD','US'), ('BAL11','Memorial Stadium',null,'Baltimore','MD','US'),\r\n",
                "('BAL12','Oriole Park at Camden Yards',null,'Baltimore','MD','US'), ('BOS01','South\r\n",
                "End Grounds I','Walpole Street Grounds','Boston','MA','US'), ('BOS02','Dartmouth\r\n",
                "Grounds','Union Park','Boston','MA','US'), ('BOS03','South End Grounds\r\n",
                "II',null,'Boston','MA','US'), ('BOS04','Congress Street\r\n",
                "Grounds',null,'Boston','MA','US'), ('BOS05','South End Grounds\r\n",
                "III',null,'Boston','MA','US'), ('BOS06','Huntington Avenue Baseball\r\n",
                "Grounds',null,'Boston','MA','US'), ('BOS07','Fenway Park',null,'Boston','MA','US'),\r\n",
                "('BOS08','Braves Field','Bee Hive','Boston','MA','US'), ('BUF01','Riverside\r\n",
                "Grounds',null,'Buffalo','NY','US'), ('BUF02','Olympic Park\r\n",
                "I',null,'Buffalo','NY','US'), ('BUF03','Olympic Park II',null,'Buffalo','NY','US'),\r\n",
                "('BUF04','International Fair Association Grounds','Federal League\r\n",
                "Park','Buffalo','NY','US'), ('CAN01','Mahaffey Park','Pastime\r\n",
                "Park','Canton','OH','US'), ('CAN02','Pastime Park',null,'Canton','OH','US'),\r\n",
                "('CHI01','Lake Front Park I','Union Base-ball Grounds','Chicago','IL','US'),\r\n",
                "('CHI02','23rd Street Park',null,'Chicago','IL','US'), ('CHI03','Lake Front Park\r\n",
                "II',null,'Chicago','IL','US'), ('CHI05','South Side Park I','Cricket Club Grounds;\r\n",
                "Union Grounds','Chicago','IL','US'), ('CHI06','West Side\r\n",
                "Park',null,'Chicago','IL','US'), ('CHI07','South Side Park\r\n",
                "II',null,'Chicago','IL','US'), ('CHI08','West Side\r\n",
                "Grounds',null,'Chicago','IL','US'), ('CHI09','South Side Park\r\n",
                "III',null,'Chicago','IL','US'), ('CHI10','Comiskey Park I','White Sox\r\n",
                "Park','Chicago','IL','US'), ('CHI11','Wrigley Field','Weeghman Park; Cubs\r\n",
                "Park','Chicago','IL','US'), ('CHI12','Guaranteed Rate Field','U.S. Cellular\r\n",
                "Field;White Sox Park; Comiskey Park II','Chicago','IL','US'), ('CIN01','Lincoln\r\n",
                "Park Grounds','Union Cricket Club Grounds','Cincinnati','OH','US'),\r\n",
                "('CIN02','Avenue Grounds',null,'Cincinnati','OH','US'), ('CIN03','Bank Street\r\n",
                "Grounds',null,'Cincinnati','OH','US'), ('CIN04','League Park\r\n",
                "I',null,'Cincinnati','OH','US'), ('CIN05','League Park\r\n",
                "II',null,'Cincinnati','OH','US'), ('CIN06','Palace of the Fans','League Park\r\n",
                "III','Cincinnati','OH','US'), ('CIN07','Crosley Field','Redland\r\n",
                "Field','Cincinnati','OH','US'), ('CIN08','Cinergy Field','Riverfront\r\n",
                "Stadium','Cincinnati','OH','US'), ('CIN09','Great American\r\n",
                "Ballpark',null,'Cincinnati','OH','US'), ('CLE01','National Association\r\n",
                "Grounds',null,'Cleveland','OH','US'), ('CLE02','League Park I','Kennard Street\r\n",
                "Park','Cleveland','OH','US'), ('CLE03','League Park II','American Association\r\n",
                "Park','Cleveland','OH','US'), ('CLE04','Brotherhood Park','Players League\r\n",
                "Park','Cleveland','OH','US'), ('CLE05','League Park III','National League Park\r\n",
                "III','Cleveland','OH','US'), ('CLE06','League Park IV','Dunn\r\n",
                "Field','Cleveland','OH','US'), ('CLE07','Cleveland Stadium','Municipal\r\n",
                "Stadium','Cleveland','OH','US'), ('CLE08','Progressive Field','Jacobs\r\n",
                "Field','Cleveland','OH','US'), ('CLE09','Cedar Avenue Driving\r\n",
                "Park',null,'Cleveland','OH','US'), ('CLL01','Euclid Beach\r\n",
                "Park',null,'Collinwood','OH','US'), ('COL01','Recreation Park\r\n",
                "I',null,'Columbus','OH','US'), ('COL02','Recreation Park\r\n",
                "II',null,'Columbus','OH','US'), ('COL03','Neil Park I',null,'Columbus','OH','US'),\r\n",
                "('COL04','Neil Park II',null,'Columbus','OH','US'), ('COV01','Star Baseball\r\n",
                "Park',null,'Covington','KY','US'), ('DAY01','Fairview\r\n",
                "Park',null,'Dayton','OH','US'), ('DEN01','Mile High\r\n",
                "Stadium',null,'Denver','CO','US'), ('DEN02','Coors Field',null,'Denver','CO','US'),\r\n",
                "('DET01','Recreation Park',null,'Detroit','MI','US'), ('DET02','Bennett\r\n",
                "Park',null,'Detroit','MI','US'), ('DET03','Burns Park','West End\r\n",
                "Park','Detroit','MI','US'), ('DET04','Tiger Stadium','Navin Field; Briggs\r\n",
                "Stadium','Detroit','MI','US'), ('DET05','Comerica Park',null,'Detroit','MI','US'),\r\n",
                "('DOV01','Fairview Park Fair Grounds',null,'Dover','DE','US'), ('ELM01','Maple\r\n",
                "Avenue Driving Park',null,'Elmira','NY','US'), ('FOR01','Grand Duchess','Hamilton\r\n",
                "Field','Fort Wayne','IN','US'), ('FOR03','Jailhouse Flats',null,'Fort\r\n",
                "Wayne','IN','US'), ('FTB01','Fort Bragg Field',null,'Fort Bragg','NC','US'),\r\n",
                "('GEA01','Geauga Lake Grounds','Beyerle_s Park','Geauga Lake','OH','US'),\r\n",
                "('GLO01','Gloucester Point Grounds',null,'Gloucester City','NJ','US'),\r\n",
                "('GLO02','Gloucester Fireworks Park',null,'Gloucester City','NJ','US'),\r\n",
                "('GRA01','Ramona Park',null,'Grand Rapids','MI','US'), ('HAR01','Harrison\r\n",
                "Field',null,'Harrison','NJ','US'), ('HOB01','Elysian\r\n",
                "Field',null,'Hoboken','NJ','US'), ('HON01','Aloha\r\n",
                "Stadium',null,'Honolulu','HI','US'), ('HOU01','Colt\r\n",
                "Stadium',null,'Houston','TX','US'), ('HOU02','Astrodome',null,'Houston','TX','US'),\r\n",
                "('HOU03','Minute Maid Park','Enron Field; Astros Field','Houston','TX','US'),\r\n",
                "('HRT01','Hartford Ball Club Grounds',null,'Hartford','CT','US'),\r\n",
                "('HRT02','Hartford Trotting Park',null,'Hartford','CT','US'), ('IND01','South\r\n",
                "Street Park',null,'Indianapolis','IN','US'), ('IND02','Seventh Street Park\r\n",
                "I',null,'Indianapolis','IN','US'), ('IND03','Bruce\r\n",
                "Grounds',null,'Indianapolis','IN','US'), ('IND04','Seventh Street Park\r\n",
                "II',null,'Indianapolis','IN','US'), ('IND05','Seventh Street Park\r\n",
                "III',null,'Indianapolis','IN','US'), ('IND06','Indianapolis\r\n",
                "Park',null,'Indianapolis','IN','US'), ('IND07','Federal League Park','Washington\r\n",
                "Park','Indianapolis','IN','US');\r\n",
                "INSERT INTO Parks VALUES ('IRO01','Windsor Beach',null,'Irondequoit','NY','US'),\r\n",
                "('JER01','Oakdale Park',null,'Jersey City','NJ','US'), ('JER02','Roosevelt\r\n",
                "Stadium',null,'Jersey City','NJ','US'), ('KAN01','Athletic Park',null,'Kansas\r\n",
                "City','MO','US'), ('KAN02','Association Park',null,'Kansas City','MO','US'),\r\n",
                "('KAN03','Exposition Park',null,'Kansas City','MO','US'), ('KAN04','Gordon and\r\n",
                "Koppel Field',null,'Kansas City','MO','US'), ('KAN05','Municipal\r\n",
                "Stadium',null,'Kansas City','MO','US'), ('KAN06','Kauffman Stadium','Royals\r\n",
                "Stadium','Kansas City','MO','US'), ('KEO01','Perry Park','Walte_s\r\n",
                "Pasture','Keokuk','IA','US'), ('LAS01','Cashman Field',null,'Las Vegas','NV','US'),\r\n",
                "('LBV01','The Ballpark at Disney_s Wide World',null,'Lake Buena Vista','FL','US'),\r\n",
                "('LON01','London Stadium',null,'London','ENG','UK'), ('LOS01','Los Angeles Memorial\r\n",
                "Coliseum',null,'Los Angeles','CA','US'), ('LOS02','Wrigley Field',null,'Los\r\n",
                "Angeles','CA','US'), ('LOS03','Dodger Stadium','Chavez Ravine','Los\r\n",
                "Angeles','CA','US'), ('LOU01','Louisville Baseball\r\n",
                "Park',null,'Louisville','KY','US'), ('LOU02','Eclipse Park\r\n",
                "I',null,'Louisville','KY','US'), ('LOU03','Eclipse Park\r\n",
                "II',null,'Louisville','KY','US'), ('LOU04','Eclipse Park\r\n",
                "III',null,'Louisville','KY','US'), ('LUD01','Ludlow Baseball\r\n",
                "Park',null,'Ludlow','KY','US'), ('MAS01','Long Island\r\n",
                "Grounds',null,'Maspeth','NY','US'), ('MIA01','Sun Life Stadium','JoeRobbie;\r\n",
                "ProPlayer; Dolphin; LandShark','Miami','FL','US'), ('MIA02','Marlins\r\n",
                "Park',null,'Miami','FL','US'), ('MID01','Mansfield Club\r\n",
                "Grounds',null,'Middletown','CT','US'), ('MIL01','Milwaukee Base-Ball\r\n",
                "Grounds',null,'Milwaukee','WI','US'), ('MIL02','Wright Street\r\n",
                "Grounds',null,'Milwaukee','WI','US'), ('MIL03','Athletic\r\n",
                "Park',null,'Milwaukee','WI','US'), ('MIL04','Lloyd Street\r\n",
                "Grounds',null,'Milwaukee','WI','US'), ('MIL05','County\r\n",
                "Stadium',null,'Milwaukee','WI','US'), ('MIL06','Miller\r\n",
                "Park',null,'Milwaukee','WI','US'), ('MIN01','Athletic\r\n",
                "Park',null,'Minneapolis','MN','US'), ('MIN02','Metropolitan\r\n",
                "Stadium',null,'Bloomington','MN','US'), ('MIN03','Hubert H. Humphrey\r\n",
                "Metrodome',null,'Minneapolis','MN','US'), ('MIN04','Target\r\n",
                "Field',null,'Minneapolis','MN','US'), ('MNT01','Estadio\r\n",
                "Monterrey',null,'Monterrey','Nuevo Leon','MX'), ('MON01','Parc Jarry','Jarry\r\n",
                "Park','Montreal','QC','CA'), ('MON02','Stade Olympique','Olympic\r\n",
                "Stadium','Montreal','QC','CA'), ('NEW01','Howard Avenue Grounds','Brewster\r\n",
                "Park','New Haven','CT','US'), ('NEW02','Hamilton Park',null,'New Haven','CT','US'),\r\n",
                "('NEW03','Geauga Lake Grounds','Beyerle_s Park','Geauga Lake','OH','US'),\r\n",
                "('NWK01','Wiedenmeyer_s Park',null,'Newark','NJ','US'), ('NYC01','Union\r\n",
                "Grounds',null,'Brooklyn','NY','US'), ('NYC02','Capitoline\r\n",
                "Grounds',null,'Brooklyn','NY','US'), ('NYC03','Polo Grounds I (Southeast\r\n",
                "Diamond)',null,'New York','NY','US'), ('NYC04','Polo Grounds II (Southwest\r\n",
                "Diamond)',null,'New York','NY','US'), ('NYC05','Washington Park\r\n",
                "I',null,'Brooklyn','NY','US'), ('NYC06','Metropolitan Park',null,'New\r\n",
                "York','NY','US'), ('NYC07','Grauer_s Ridgewood Park','Ridgewood Park\r\n",
                "I','Queens','NY','US'), ('NYC08','Washington Park II',null,'Brooklyn','NY','US'),\r\n",
                "('NYC09','Polo Grounds III',null,'New York','NY','US'), ('NYC10','Polo Grounds\r\n",
                "IV',null,'New York','NY','US'), ('NYC11','Eastern Park',null,'Brooklyn','NY','US'),\r\n",
                "('NYC12','Washington Park III',null,'Brooklyn','NY','US'), ('NYC13','Hilltop\r\n",
                "Park',null,'New York','NY','US'), ('NYC14','Polo Grounds V',null,'New\r\n",
                "York','NY','US'), ('NYC15','Ebbets Field',null,'Brooklyn','NY','US'),\r\n",
                "('NYC16','Yankee Stadium I',null,'New York','NY','US'), ('NYC17','Shea\r\n",
                "Stadium','William A. Shea Stadium','New York','NY','US'), ('NYC18','Wallace_s\r\n",
                "Ridgewood Park','Ridgewood Park II','Queens','NY','US'), ('NYC19','Washington Park\r\n",
                "IV',null,'Brooklyn','NY','US'), ('NYC20','Citi Field',null,'New York','NY','US'),\r\n",
                "('NYC21','Yankee Stadium II',null,'New York','NY','US'), ('OAK01','Oakland-Alameda\r\n",
                "County Coliseum','Network Associates Coliseum','Oakland','CA','US'), ('OMA01','TD\r\n",
                "Ameritrade Park',null,'Omaha','NE','US'), ('PEN01','East End Park','Pendleton\r\n",
                "Park','Cincinnati','OH','US'), ('PHI01','Jefferson Street Grounds','Athletics\r\n",
                "Park','Philadelphia','PA','US'), ('PHI02','Centennial\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI03','Oakdale\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI04','Recreation\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI05','Keystone\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI06','Huntingdon Grounds\r\n",
                "I',null,'Philadelphia','PA','US'), ('PHI07','Forepaugh\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI08','University of Penn. Athletic\r\n",
                "Field',null,'Philadelphia','PA','US'), ('PHI09','Baker\r\n",
                "Bowl',null,'Philadelphia','PA','US'), ('PHI10','Columbia\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI11','Shibe Park','Connie Mack\r\n",
                "Stadium','Philadelphia','PA','US'), ('PHI12','Veterans\r\n",
                "Stadium',null,'Philadelphia','PA','US'), ('PHI13','Citizens Bank\r\n",
                "Park',null,'Philadelphia','PA','US'), ('PHI14','Huntingdon Grounds\r\n",
                "II',null,'Philadelphia','PA','US'), ('PHO01','Chase Field','Bank One\r\n",
                "Ballpark','Phoenix','AZ','US'), ('PIT01','Union Park',null,'Pittsburgh','PA','US'),\r\n",
                "('PIT02','Exposition Park I','Lower Field','Pittsburgh','PA','US'),\r\n",
                "('PIT03','Exposition Park II','Upper Field','Pittsburgh','PA','US'),\r\n",
                "('PIT04','Recreation Park',null,'Pittsburgh','PA','US'), ('PIT05','Exposition Park\r\n",
                "III',null,'Pittsburgh','PA','US'), ('PIT06','Forbes\r\n",
                "Field',null,'Pittsburgh','PA','US'), ('PIT07','Three Rivers\r\n",
                "Stadium',null,'Pittsburgh','PA','US'), ('PIT08','PNC\r\n",
                "Park',null,'Pittsburgh','PA','US'), ('PRO01','Adelaide Avenue\r\n",
                "Grounds',null,'Providence','RI','US'), ('PRO02','Messer Street\r\n",
                "Grounds',null,'Providence','RI','US'), ('RCK01','Agricultural Society Fair\r\n",
                "Grounds',null,'Rockford','IL','US'), ('RIC01','Richmond Fair\r\n",
                "Grounds',null,'Richmond','VA','US'), ('RIC02','Allens\r\n",
                "Pasture',null,'Richmond','VA','US'), ('ROC01','Culver Field\r\n",
                "I',null,'Rochester','NY','US'), ('ROC02','Culver Field\r\n",
                "II',null,'Rochester','NY','US'), ('ROC03','Ontario Beach\r\n",
                "Grounds',null,'Rochester','NY','US'), ('SAI01','St. George Cricket\r\n",
                "Grounds',null,'New York','NY','US'), ('SAN01','Qualcomm Stadium','San Diego/Jack\r\n",
                "Murphy Stadium','San Diego','CA','US'), ('SAN02','PETCO Park',null,'San\r\n",
                "Diego','CA','US');\r\n",
                "INSERT INTO Parks VALUES ('SEA01','Sick_s Stadium',null,'Seattle','WA','US'),\r\n",
                "('SEA02','Kingdome',null,'Seattle','WA','US'), ('SEA03','Safeco Field','T-Mobile\r\n",
                "Park','Seattle','WA','US'), ('SFO01','Seals Stadium',null,'San\r\n",
                "Francisco','CA','US'), ('SFO02','Candlestick Park','3Com Park','San\r\n",
                "Francisco','CA','US'), ('SFO03','AT&T Park','Pacific Bell Park; SBC Park','San\r\n",
                "Francisco','CA','US'), ('SJU01','Estadio Hiram Bithorn',null,'San Juan',null,'PR'),\r\n",
                "('SPR01','Hampden Park Race Track','Springfield Track','Springfield','MA','US'),\r\n",
                "('STL01','Red Stockings Base Ball Park',null,'St. Louis','MO','US'),\r\n",
                "('STL02','Grand Avenue Park',null,'St. Louis','MO','US'), ('STL03','Sportsman_s\r\n",
                "Park I',null,'St. Louis','MO','US'), ('STL04','Union Grounds',null,'St.\r\n",
                "Louis','MO','US'), ('STL05','Robison Field',null,'St. Louis','MO','US'),\r\n",
                "('STL06','Sportsman_s Park II',null,'St. Louis','MO','US'), ('STL07','Sportsman_s\r\n",
                "Park III','Busch Stadium I','St. Louis','MO','US'), ('STL08','Handlan_s\r\n",
                "Park','Federal League Park','St. Louis','MO','US'), ('STL09','Busch Stadium\r\n",
                "II',null,'St. Louis','MO','US'), ('STL10','Busch Stadium III',null,'St.\r\n",
                "Louis','MO','US'), ('STP01','Tropicana Field',null,'St. Petersburg','FL','US'),\r\n",
                "('SYD01','Sydney Cricket Ground',null,'Sydney','New South Wales','AU'),\r\n",
                "('SYR01','Star Park I','Newell Park','Syracuse','NY','US'), ('SYR02','Star Park\r\n",
                "II',null,'Syracuse','NY','US'), ('SYR03','Iron Pier',null,'Syracuse','NY','US'),\r\n",
                "('THR01','Three Rivers Park',null,'Three Rivers','NY','US'), ('TOK01','Tokyo\r\n",
                "Dome',null,'Tokyo','Tokyo','JP'), ('TOL01','League Park',null,'Toledo','OH','US'),\r\n",
                "('TOL02','Tri-State Fair Grounds',null,'Toledo','OH','US'), ('TOL03','Speranza\r\n",
                "Park',null,'Toledo','OH','US'), ('TOL04','Armory Park',null,'Toledo','OH','US'),\r\n",
                "('TOR01','Exhibition Stadium',null,'Toronto','ON','CA'), ('TOR02','Rogers\r\n",
                "Centre','Skydome','Toronto','ON','CA'), ('TRO01','Haymakers_\r\n",
                "Grounds',null,'Troy','NY','US'), ('TRO02','Putnam Grounds',null,'Troy','NY','US'),\r\n",
                "('WAR01','Rocky Point Park',null,'Warwick','RI','US'), ('WAS01','Olympic\r\n",
                "Grounds',null,'Washington','DC','US'), ('WAS02','National\r\n",
                "Grounds',null,'Washington','DC','US'), ('WAS03','Capitol\r\n",
                "Grounds',null,'Washington','DC','US'), ('WAS04','Athletic\r\n",
                "Park',null,'Washington','DC','US'), ('WAS05','Swampoodle\r\n",
                "Grounds',null,'Washington','DC','US'), ('WAS06','Boundary\r\n",
                "Field',null,'Washington','DC','US'), ('WAS07','American League Park\r\n",
                "I',null,'Washington','DC','US'), ('WAS08','American League Park\r\n",
                "II',null,'Washington','DC','US'), ('WAS09','Griffith\r\n",
                "Stadium',null,'Washington','DC','US'), ('WAS10','Robert F. Kennedy Stadium','D.C.\r\n",
                "Stadium','Washington','DC','US'), ('WAS11','Nationals\r\n",
                "Park',null,'Washington','DC','US'), ('WAT01','Troy Ball Club\r\n",
                "Grounds',null,'Watervliet','NY','US'), ('WAV01','Waverly\r\n",
                "Fairgrounds',null,'Waverly','NJ','US'), ('WEE01','Monitor\r\n",
                "Grounds',null,'Weehawken','NJ','US'), ('WHE01','Island\r\n",
                "Grounds',null,'Wheeling','WV','US'), ('WIL01','Union Street\r\n",
                "Park',null,'Wilmington','DE','US'), ('WIL02','BB&T Ballpark at Bowman\r\n",
                "Field',null,'Williamsport','PA','US'), ('WNY01','West New York Field Club\r\n",
                "Grounds',null,'West New York','NJ','US'), ('WOR01','Agricultural County Fair\r\n",
                "Grounds I',null,'Worcester','MA','US'), ('WOR02','Agricultural County Fair Grounds\r\n",
                "II',null,'Worcester','MA','US'), ('WOR03','Worcester Driving Park\r\n",
                "Grounds',null,'Worcester','MA','US');\r\n",
                "Go\r\n",
                "select count(*) from Parks"
            ],
            "metadata": {
                "azdata_cell_guid": "a29b04f5-98c3-490c-97a6-6951ef3a0fca",
                "language": "sql"
            },
            "outputs": [
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "Commands completed successfully."
                    },
                    "metadata": {}
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "(0 rows affected)"
                    },
                    "metadata": {}
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "(100 rows affected)"
                    },
                    "metadata": {}
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "(100 rows affected)"
                    },
                    "metadata": {}
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "(55 rows affected)"
                    },
                    "metadata": {}
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "(1 row affected)"
                    },
                    "metadata": {}
                },
                {
                    "output_type": "display_data",
                    "data": {
                        "text/html": "Total execution time: 00:00:00.216"
                    },
                    "metadata": {}
                },
                {
                    "output_type": "execute_result",
                    "execution_count": 10,
                    "data": {
                        "application/vnd.dataresource+json": {
                            "schema": {
                                "fields": [
                                    {
                                        "name": "(No column name)"
                                    }
                                ]
                            },
                            "data": [
                                {
                                    "(No column name)": "255"
                                }
                            ]
                        },
                        "text/html": "<table><tr><th>(No column name)</th></tr><tr><td>255</td></tr></table>"
                    },
                    "metadata": {}
                }
            ],
            "execution_count": 10
        }
    ]
}